# Generated by Django 6.0.4 on 2026-04-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_formulario'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoTesouro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_cru', models.JSONField(verbose_name='Dados Brutos do Tesouro')),
                ('data_captura', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Histórico do Tesouro',
                'verbose_name_plural': 'Históricos do Tesouro',
                'ordering': ['-data_captura'],
            },
        ),
    ]
